# -*- coding: utf-8 -*-
"""DNA sequencing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6ZaxkUBavBWHY6Jj7md3aeqVRr1haRl

Imports
"""

!pip install biopython
import matplotlib.pyplot as plt


from Bio.Seq import Seq
#!pip install ipywidgets

"""Functions and DNA Analysis"""

# Making sure user input is all caps
dna = Seq(input('Enter coding strand DNA here: ').upper())
# Raise error for no input
if len(dna) == 0:
  raise ValueError('No DNA sequence input')

# Function to detect Open Reading Frames (ORFs) in DNA sequence
# ORFs are sections of DNA that code for amino acids (exons)
# An ORF starts with ATG (start codon) and end with TAA, TAG, or TGA (stop codons)
def find_orfs(dna):
  start_pos = [] # Stores every ATG codon found
  orfs = [] # Stores every ORF detected
  # Reads 3 bases (codon) at a time
  for base in range(0,len(dna)-3+1):
    codon = dna[base:base+3]
    if codon == 'ATG':
      start_pos.append(base) # Found and saved position of start codon
  for start in start_pos:
    for s in range(start, len(dna),3):
      codon = dna[s:s+3]
      if codon in ['TAA','TAG','TGA']: # Find stop codons
        orfs.append(dna[start:s+3])
        break
  return orfs

# Function to translate ORFs only
def translate_orfs(orfs):
  rna=[] # Holds mRNA sequence
  aa=[] # Holds amino acid sequence
  for orf in orfs:
    # Using biopython library to automatically transcribe and translate
    rna.append(str((orf.transcribe())))
    aa.append(str((orf.translate())))
  return rna, aa

# GC content: Percentage of bases that are Guanine or Cytosine
# G-C form 3 hydrogen bonds versus A-T's 2 H-bonds
# which makes GC rich DNA more difficult to denature with heat
def gc_content(dna):
  gc_count = dna.count('G') + dna.count('C')
  GCPercent = gc_count/len(dna)*100
  # Simple stability classification based on 50% GC content threshold
  if GCPercent >= 50:
    stability = 'High'
  else:
    stability = 'Moderate'
  return GCPercent, stability

# Runs analysis
orfs = find_orfs(dna)
rna, aa = translate_orfs(orfs)
GCPercent, stability = gc_content(dna)

# Prints analysis
print('Exons: ',orfs); print('RNA sequence: ',rna);print('Amino acid sequence: ', aa)
print('Guanine/Cytosine content: ', GCPercent);print('Molecule stability: ', stability)

"""**CHART**: Nucleotide Composition Bar Graph


"""

# Counting how many of each nucleotide appears in sequence
bases = [dna.count('A'),dna.count('T'),dna.count('G'),dna.count('C')]
labels = ['A','T','G','C']
# Each nucleotide is assigned a color for easy reading
# Using matplotlib to graph
plt.bar(height=bases, x=labels, color = ['#a31a1a','#1963bd','#579c25','#d4a331'])
plt.title('Nucleotide count')
plt.xlabel('Nucleotide')
plt.ylabel('Base number')
plt.show()

"""**CHART**: K-mer GC Content Graph"""

# A k-mer is a short substring of a length, n (here n is 5)
# A window of size n is slid across the DNA sequence, and calculates GC% at
# each position to show how GC content varies across different regions of DNA
n=5
def plot_kmers(dna,n):
  # Creates substrings of length n using sliding window
  window = [dna[i:i+n] for i in range(0,len(dna) - n+1)]
  percent_list = []
  for w in window:
    countGC2 = w.count('G') + w.count('C')
    percent2 = countGC2/len(w)*100
    percent_list.append(percent2)
  x = range(len(window)) # x-axis: window index (position along DNA sequence)
  return percent_list, x

percent_list, x = plot_kmers(dna,n)

plt.title('K-mer graph')
plt.xlabel('Window index')
plt.ylabel('GC Composition (%)')
plt.plot(x,percent_list, color='#1963bd')
plt.show()

"""Combine all my functions into one big function!"""

#dna = Seq(input('Enter coding strand DNA here: ').upper())
#if len(dna) == 0:
  #raise ValueError('No DNA sequence input')
import ipywidgets as widgets

dna_input = widgets.Text(value='',placeholder='Enter coding strand DNA sequence', description='DNA')
display(dna_input)

dna = Seq(dna_input.value.upper())

def analyze_dna(dna, n):
    orfs = find_orfs(dna)
    rna, aa = translate_orfs(orfs)
    gc_percent, stability = gc_content(dna)
    percent_list, x = plot_kmers(dna, n)
    return {
        "orfs": orfs,
        "rna": rna,
        "aa": aa,
        "gc_percent": gc_percent,
        "stability": stability,
        "kmer_x": x,
        "kmer_gc": percent_list
    }

results = analyze_dna(dna,n)

display(results)

import ipywidgets as widgets

# 1. Create the button
button = widgets.Button(description="Click Me!")

# 2. Define what happens when clicked
def on_button_clicked(b):
    print("Button clicked!")

# 3. Link the function to the button
button.on_click(on_button_clicked)

# 4. Display it
display(button)