# -*- coding: utf-8 -*-
"""DNA sequencing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6ZaxkUBavBWHY6Jj7md3aeqVRr1haRl

# DNA Sequencing

Imports
"""

!pip install biopython
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact
from IPython.display import HTML, display
import numpy as np


from Bio.Seq import Seq
!pip install ipywidgets

import google.colab.output

"""Functions and DNA Analysis"""

from ipywidgets.widgets.widget_output import clear_output

dna = Seq(input('Enter coding strand DNA here: ').upper())

# Biopython automatically checks for invalid bases
# But I'm putting this here just in case!
valid_bases = set('ATGCatgc')

# Raise error for no input
if len(dna) == 0:
  raise ValueError('No DNA sequence input')
invalid=set(str(dna))-valid_bases
if invalid:
  raise ValueError(f'Invalid bases found: {invalid}. Only A,T,G,C are allowed (not case sensitive).')




# Function to detect Open Reading Frames (ORFs) in DNA sequence
# ORFs are sections of DNA that code for amino acids (exons)
# An ORF starts with ATG (start codon) and end with TAA, TAG, or TGA (stop codons)
def find_orfs(dna):
  start_pos = [] # Stores every ATG codon found
  orfs = [] # Stores every ORF detected
  # Reads 3 bases (codon) at a time
  for base in range(0,len(dna)-3+1):
    codon = dna[base:base+3]
    if codon == 'ATG':
      start_pos.append(base) # Found and saved position of start codon
  for start in start_pos:
    for s in range(start, len(dna),3):
      codon = dna[s:s+3]
      if codon in ['TAA','TAG','TGA']: # Find stop codons
        orfs.append(dna[start:s+3])
        break
  return orfs

# Function to translate ORFs only
def translate_orfs(orfs):
  rna=[] # Holds mRNA sequence
  aa=[] # Holds amino acid sequence
  for orf in orfs:
    # Using biopython library to automatically transcribe and translate
    rna.append(str((orf.transcribe())))
    aa.append(str((orf.translate())))
  return rna, aa

# GC content: Percentage of bases that are Guanine or Cytosine
# G-C form 3 hydrogen bonds versus A-T's 2 H-bonds
# which makes GC rich DNA more difficult to denature with heat
def gc_content(dna):
  gc_count = dna.count('G') + dna.count('C')
  GCPercent = gc_count/len(dna)*100
  # Simple stability classification based on 50% GC content threshold
  if GCPercent >= 50:
    stability = 'High'
  else:
    stability = 'Moderate'
  return GCPercent, stability

def analyze_dna(dna):
  # Runs analysis
  orfs = find_orfs(dna)
  rna, aa = translate_orfs(orfs)
  GCPercent, stability = gc_content(dna)
  return {"o": orfs, 'r': rna, 'a': aa, 'GC': GCPercent, 's': stability}

results = analyze_dna(dna)


print("Exons:", results['o'])
print("RNA Sequence:", results['r'])
print("Amino Acid Sequence:", results['a'])
print("GC Composition:", results['GC'],'%')
print("DNA Stability is:", results['s'])

"""**CHART**: Nucleotide Composition Bar Graph


"""

# Counting how many of each nucleotide appears in sequence
bases = [dna.count('A'),dna.count('T'),dna.count('G'),dna.count('C')]
labels = ['A','T','G','C']
# Each nucleotide is assigned a color for easy reading
# Using matplotlib to graph
plt.bar(height=bases, x=labels, color = ['#a31a1a','#1963bd','#579c25','#d4a331'])
plt.title('Nucleotide count')
plt.xlabel('Nucleotide')
plt.ylabel('Base number')
plt.show()

"""**CHART**: K-mer Sliding Window GC Content Graph

**A disclaimer about my sliding windows plots!**

Each sliding window is treated independently of the windows before or after it.
Because of this, the DNA melting behavior is simplified.
"""

# A k-mer is a short substring of a length, n
# A window of size n is slid across the DNA sequence, and calculates GC% at
# each position to show how GC content varies across different regions of DNA
def plot_kmers(dna,n):

  # Creates substrings of length n using sliding window
  window = [dna[i:i+n] for i in range(0,len(dna) - n+1)]
  percent_list = []
  for w in window:
    countGC2 = w.count('G') + w.count('C')
    percent2 = countGC2/len(w)*100
    percent_list.append(percent2)
  x = range(len(window)) # x-axis: window index (position along DNA sequence)
  return percent_list, x

@interact(n=widgets.IntSlider(min=5,max=30,step=1,value=10, description = 'Window size'))
def f(n):
  percent_list, x= plot_kmers(dna,n)
  plt.title('K-mer graph')
  plt.xlabel('Window index')
  plt.ylabel('GC Composition (%)')
  plt.plot(x,percent_list, color='#1963bd')
  plt.show()

"""Plus a **SIMPLIFIED MODEL**: DNA Thermal Opening

> Context

DNA "breathes". Its base pairs will constantly open and close, so GC and AT content can impact that.
This breathing is due to the denaturing of DNA via heat. To quantify stability for a simple model, I'll multiply the GC content fraction by 3 (because GC pairs make 3 H-bonds) and AT content fraction by 2 (because AT pairs make 2 H-bonds). Base stacking can also impact denaturation, but for simplicity, I'm assuming only H-bond count impacts DNA breathing for now.
"""

def thermo_stability(dna,n):
  window = [dna[i:i+n] for i in range(0,len(dna) - n+1)]

  thermo_model = []
  open_tend = []

  for w in window:
    G = w.count('G')
    C = w.count('C')
    A = w.count('A')
    T = w.count('T')

    score = (G+C)/len(w)*3 # Standardizing stability based on GC content
    score2 = (A+T)/len(w)*2 # Standardizing stability based on AT content

    thermo_model.append(score+score2)
    inverse = 3-(score+score2) # Flips the relationship
    open_tend.append(inverse)
  open_tend=np.array(open_tend)
  thermo_model=np.array(thermo_model)
  if len(open_tend)>1:
    open_norm = (open_tend-min(open_tend))/(max(open_tend)-min(open_tend)) # min/max normalization
  else:
    open_norm=open_tend

  if len(thermo_model)>1:
    thermo_norm = (thermo_model-min(thermo_model))/(max(thermo_model)-min(thermo_model))
  else:
    thermo_norm=thermo_model
  z = range(len(window))
  return thermo_norm, z, open_norm

# Threshold could be any number from 0-1, but I chose 0.5 because it's in the
# middle of 0-1
threshold = 0.5

@interact(n=widgets.IntSlider(min=5,max=30,step=1,value=10,description = 'Window size'),)
def g(n):
  thermo_norm, z, open_norm= thermo_stability(dna,n)
  plt.title('Normalized Stability Model')
  plt.xlabel('Window index')
  plt.ylabel('Normalized stability score')
  plt.plot(z, thermo_norm, color='#9c1111')
  plt.show()

  plt.title('Normalized Opening Tendency')
  plt.xlabel('Window index')
  plt.ylabel('Normalized opening tendency')
  plt.fill_between(z, open_norm, threshold, where=[o>threshold for o in open_norm],
                   color='red', alpha=0.3, label="Unstable regions")
  plt.plot(z, open_norm, color='#088555')
  plt.legend()
  plt.show()

"""**Simplified Model**: Santa Lucia Model - Nearest Neighbor Model

Deals with DNA base pair stacking!

> Note!

For salt correction, I use an older formula. This formula assumed monovalent salts (1:1 charge ratio, so 1 cation and 1 anion when disolved) like NaCl.
Most Santa Lucia models use much more advanced salt corrections.





"""

## ~ TESTING DIFF DNA SEQ FOR OPEN AND CLOSE PROB.~ ##
# dna = Seq('CATAG')
# Test results: P(open) of AAAAA > P(open) of CATAG > P(open) of GGGGG

# CA/GT and TG/AC are the same duplex when viewed from opposite strands
# That's why CA and TG have the same ∆H and ∆S
# Nearest neighbor parameters in (∆H [cal/mol], ∆S [cal/mol*K] )
# Source: Source: https://www.pnas.org/doi/10.1073/pnas.95.4.1460
nn_par = {'AA': (-7900,-22.2), 'TT': (-7900,-22.2),
          'AT': (-7200 ,-20.4), 'TA': (-7200,-21.3),
          'CA': (-8500, -22.7),'TG': (-8500, -22.7),
          'GT': (-8400, -22.4),'AC': (-8400, -22.4),
          'CT': (-7800, -21.0),'AG': (-7800, -21.0),
          'GA': (-8200, -22.2),'TC': (-8200, -22.2),
          'CG': (-10600, -27.2),'GC': (-9800, -24.4),
          'GG': (-8000, -19.9),'CC': (-8000, -19.9),}

def melting_DNA(dna,n, nn_par, salt, temp):
  window = [dna[i:i+n] for i in range(0,len(dna) - n+1)]

  if len(dna) <= 14:
    print("Disclaimer: At a length of 14 base pairs or below, SantaLucia model becomes less accurate")
  melting_pt = []
  close_prob = []
  open_prob = []

  for w in window:
    G = w.count('G')
    C = w.count('C')
    A = w.count('A')
    T = w.count('T')


                  ##-- ~~ -Info on SantaLucia- ~~ --##

    # SantaLucia formula is tm = ∆H/∆S + Rln(C) - 273.15
    # Where tm is melting point, ∆H is change in enthalpy,
    # ∆S is change in entropy, R is gas constant (1.987 cal/mol*K)
    # and C is DNA strand concentration

    # Using equilibrium constants (K), we get C/4
    # If the sequence is self-complementary (can bind to itself), C/4 is not
    # needed. But for this model, we have to assume not all sequences are
    # self-complementary

    # 5' - GAATTC - 3' is self complementary.
    # If you flip it: 3' - CTTAAG - 5', its the same as the complementary
    # strand: 5' - CTTAAG - 3'


    r = 1.987

    # PCR primers are approzimately 100-500 nM
    # I'm using 300 nM as an approximate concentration
    # I'm using 10^-9 to convert nM to M
    c = 300e-9
    dh, ds = 0, 0

    # Looks at the first and last bases in the window
    for end in [w[0],w[-1]]:
      # Checks to see if the end contains G or C
      if end in ('G','C'):
        # adding penalties
        # Source: https://www.pnas.org/doi/10.1073/pnas.95.4.1460
        dh += 100; ds += -2.8
      else:
        dh += 2300; ds += 4.1


    # A/T ends have a penalty added because A/T bonds only contain 2 H-bonds
    # This means ends with A/T 'fray' more easily than ends with G/C

    for i in range(len(w) - 1):
      pair = w[i:i+2]
      h, s = nn_par.get(pair,(-8430, -22.37)) # .get(key, fallback)
      # (-8430,-22.37) is the mean of the data in the nm_par table

      # Use += to add s on top of everything in ds instead of replacing values
      # Mimics behavior of base pair stacking
      ds += s
      dh += h

    # SantaLucia equation
    tm = dh/(ds+r*np.log(c/4)) - 273.15

    # Owczarazy salt correction
    # Source: https://biopython.org/docs/1.74/api/Bio.SeqUtils.MeltingTemp.html
    # SantaLucia parameters assume NaCl concentration of 1M
    tm2 = tm + (16.6*np.log10(salt))

    # ∆G = ∆H - T∆S
    # Calculate ∆G so we can use the equilibrium constant (K) for opening prob.
    kelvins = temp + 273.15
    dg = dh - (kelvins*ds)

    # To find K with a known ∆G, use:
    # ∆G = -RTln(K)
    # Rearrange to isolate K:
    # e^(∆G/-RT) = K
    # P_open = K/(1+K)
    ## Why: DNA is Open <-> Closed, so K = Closed/Open (product/reactant)
    ## Open = K*closed
    ## Probability of open: Open/Open+Closed
    ## K*Closed/K*Closed+Closed -> Factor out Closed
    ## K/(K+1)

    K = np.exp(dg/(-r*kelvins))
    P_close = K/(K+1)
    P_open = 1 - P_close
    close_prob.append(P_close)
    open_prob.append(P_open)

    melting_pt.append(tm2)



  y = range(len(window))
  return melting_pt,y, close_prob, open_prob

# Salt concentrations in Santa Lucia models usually range from 50 mM to 1 M
@interact(n=widgets.IntSlider(min=5,max=30,step=1,value=10, description='Window Size'),
          temp=widgets.IntSlider(min=0,max=100,step=1,value=25, description='Temp. (C˚)'),
          # FloatLogSlider is automatically at log base 10
          salt=widgets.FloatLogSlider(min=-3,max=0,step=0.05,value=1, description='Salt (M)'))
def f(n, temp, salt):
  melting_pt,y, close_prob, open_prob = melting_DNA(dna,n, nn_par, salt, temp)
  plt.title('Melting Point K-mer Plot')
  plt.xlabel('Window index')
  plt.ylabel('Melting Point (C˚)')
  plt.fill_between(y,melting_pt, temp, where=[temp>tm2 for tm2 in melting_pt],
                   color = 'red', alpha=0.3, label = 'Denatured regions')
  plt.plot(y, melting_pt, color='#9c1111')
  plt.legend()
  plt.show()
  plt.title('Opening Probability')
  plt.xlabel('Window index')
  plt.ylabel('Probability')
  plt.plot(y, open_prob, color='red')
  plt.show()
  plt.title('Opening Probability')
  plt.xlabel('Window index')
  plt.ylabel('Probability')
  plt.plot(y, close_prob, color='blue')
  plt.show()
  #print('C',close_prob); print('O',open_prob)

"""**Validation of SantaLucia Model**:

I used the DNA sequence 5’-GTAAAACGACGGCCAGT (Primer M13 (-20) (universal)) to validate my model.
I tested it at window size = 10 and salt concentration = 1M.
The model had melting temperatures approaching ~52˚C at around window index 5.

Sliding Windows:

0. **G**TAAAA**CG**A**C**
1. TAAAA**CG**A**CG**
2. AAAA**CG**A**CGG**
3. AAA**CG**A**CGGC**
4. AA**CG**A**CGGCC**
5. A**CG**A**CGGCC**A
6. **CG**A**CGGCC**A**G**
7. **G**A**CGGCC**A**G**T

Window index 5 is GC-rich, which is why it shows a tm value of 52˚C.

According to
https://www.sciencegateway.org/protocols/cellbio/appendix/cprimers.htm
this primer has a melting temperature of around 52˚C - 55˚C.

Please note that the windows are independent instead of treating the primer as a single system. So exact agreement with tm values is not expected for now.

Testing HTML code for UI
"""

from google.colab import output
from IPython.display import clear_output

def analyze(dna,n,temp,salt):

  clear_output(wait=True)
  dispUI()

  dna = dna.upper()
  n=int(n)
  temp=int(temp)
  salt=float(salt)

  if 0 == len(dna):
    print('Please enter a DNA sequence.')
    return
  if n > len(dna):
    print('Window size cannot exceed sequence length.')
    return

  gc = gc_content(dna)
  gc_card.value = f"""
      <div style='
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:10px;
          background-color: #ffddc9;'>

          <h3 style='margin:0;color:#8a1a43;'>GC content</h3>

          <p style='font-size:18px;color:#8a1a43;'>{gc[0]:.1f}%<br>
          {gc[1]}</p>
      <div>"""

  orfs=find_orfs(dna)
  orf_card.value = f"""
      <div style='
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:10px;
          background-color: #ffddc9;'>

          <h3 style='margin:0;color:#8a1a43;'>ORFs</h3>

          <p style='font-size:18px;color:#8a1a43;'>{len(orfs)} found</p>
      <div>"""

  melting_pt,y, close_prob, open_prob = melting_DNA(
      dna,n, nn_par, salt, temp)
  tm_card.value = f"""
      <div style='
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:10px;
          background-color: #ffddc9;>

          <h3 style='margin:0;color:#8a1a43;'>Melting temperature</h3>

          <p style='font-size:18px;color:#8a1a43;'>{np.mean(melting_pt):.2f} ˚C</p>
      <div>"""


  print('Sliding window size:',n); print('Temperature:',temp,'C˚')
  print('Salt concentration:',salt,'M');print('GC percent composition:',gc)
  print('ORFs found:',len(orfs));print('ORFs:',orfs)

  plt.title('Melting Point K-mer Plot')
  plt.xlabel('Window index')
  plt.ylabel('Melting Point (C˚)')
  plt.fill_between(y,melting_pt, temp, where=[temp>tm2 for tm2 in melting_pt],
                   color = 'red', alpha=0.3, label = 'Denatured regions')
  plt.plot(y, melting_pt, color='#9c1111')
  plt.legend()
  plt.show()
  plt.title('Opening Probability')
  plt.xlabel('Window index')
  plt.ylabel('Probability')
  plt.plot(y, open_prob, color='red')
  plt.show()
  plt.title('Opening Probability')
  plt.xlabel('Window index')
  plt.ylabel('Probability')
  plt.plot(y, close_prob, color='blue')
  plt.show()

output.register_callback('Analyze_dna',analyze)

def dispUI():
  display(HTML("""
        <style>
          .card{
            border: 5px solid #8a1a43;
            border-radius: 10px;
            padding:15px;
            width: 400px;
            background-color: #ffddc9;
            margin:auto;
          }
          </style>
        <div class='card'>

          <h1 style='color:#1c1d29;text-align:center;font-family:calibri'>
            DNA Stability Analyzer</h1>

          <hr style='border: 1px solid #471529;border-radius: 5px''>
          <hr style='border: 1px solid #471529;border-radius: 5px''>

          <p style='color:#7d2828;text-align:center;font-family:calibri'>
            This is a mini beginner biopython project!
            <br>Here, you can analyze ORFs, opening and closing probability, and
              melting point!
          </p>

          <input
            id='dna'
            type='text'
            placeholder='Enter DNA Sequence'
            style = 'display:grid; margin:auto; width:80%;border: 2px solid #304152;border-radius: 5px; background-color:white; text-align:center;font-family:calibri'
            >
            <br><br>

          <h2 style='color:#1c1d29;text-align:center;font-family:calibri'>Analysis Parameters</h2>
            <br>

          <label style='color:#7d2828; text-align:center; font-family:calibri'
          for='n'>Window size:
          <span id="n_disp">10</span>
          </label>
          <input
            type='range'
            id='n_slide'
            min='5'
            max='30'
            style = 'display:grid; margin:auto; width:70%;accent-color:#1578d4'
            value='10'
            oninput='up1(this.value)'
            onchange='runAn1();'
            >
            <br>

          <label style='color:#7d2828; text-align:center; font-family:calibri'
          for='C'>Temperature (C˚):
          <span id="C_disp">25</span>
          </label>
          <input
            type='range'
            id='C_slide'
            min='0'
            max='100'
            value='25'
            style = 'display:grid; margin:auto; width:70%;accent-color:#d42b15'
            oninput='up2(this.value)'
            onchange='runAn1();'
            >
            <br>

        <label style='color:#7d2828; text-align:center; font-family:calibri'
          for='M'>Salt Concentration (M):
          <span id="M_disp">0.5</span>
          </label>
          <input
            type='range'
            id='M_slide'
            min='0.00'
            max='1.00'
            step='0.05'
            value='0.50'
            style = 'display:grid; margin:auto; width:70%;accent-color:#c47310;'
            oninput='up3(this.value)'
            onchange='runAn1();'
            >
            <br><br>

    <script>
            function runAn1(){
            google.colab.kernel.invokeFunction(
            'Analyze_dna',[document.getElementById('dna').value,
            document.getElementById('n_slide').value,
            document.getElementById('C_slide').value,
            document.getElementById('M_slide').value],{});
            }
    </script>

          <button type='button'
          onclick="runAn1()"
          style='display:grid; margin:auto; width:30%;border: 2px solid #26451b;border-radius: 5px; background-color:#557532; color: #141716; text-align:center;font-family:calibri'
    >Analyze Sequence</button>
    <br>



          </div>

    <script>
        function up1(val) {
        document.getElementById('n_disp').textContent = val;
        }
        function up2(val) {
        document.getElementById('C_disp').textContent = val;
        }
        function up3(val) {
        document.getElementById('M_disp').textContent = val;
        }
    </script>
    </div>
    """))

dispUI()

# This cell automatically updates when the above UI sequence is analyzed
# I had to put the []_card.value sections in the above cell in the analyze()
# function. The analyze function deletes once the button is pressed, and the
# variables don't exist until the actual analysis is being preformed
# So putting that section under the analyze function helps to make sure the
# variables are called.


# This is making empty cards

gc_card = widgets.HTML("""
      <style>
        .card{
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:15px;
          width: 400px;
          background-color: #ffddc9;
          margin:auto;
        }
        </style>
      <div>""")

orf_card = widgets.HTML("""
      <style>
        .card{
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:15px;
          width: 400px;
          background-color: #ffddc9;
          margin:auto;
        }
        </style>
      <div>""")

tm_card = widgets.HTML("""
      <style>
        .card{
          border: 2px solid #8a1a43;
          border-radius: 10px;
          padding:15px;
          width: 400px;
          background-color: #ffddc9;
          margin:auto;
        }
        </style>
      <div>""")


# This is organizing everything
# HBox ensures that the cards are organized horizontally

# I plan in the future to add the graphs to these cards

display(widgets.HBox([gc_card,orf_card,tm_card],layout=widgets.Layout(justify_content='space-around')))